version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "josepderiu"
    assignees:
      - "josepderiu"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    # Group all patch updates into a single PR
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
    # Ignore major version updates for stable dependencies
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "josepderiu"
    commit-message:
      prefix: "ci"
    labels:
      - "github-actions"
      - "automated"
