name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  validate:
    name: Validate Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint:all

      - name: Format check
        run: npm run format:check

      - name: Build
        run: npm run build

      - name: Test with coverage
        run: npm run test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-ci
          fail_ci_if_error: false

      - name: Security audit
        run: npm audit --audit-level=moderate

      - name: Verify pinned versions
        run: npm run security:check-versions

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            dist/
            coverage/
          retention-days: 30
